# Generated by Django 6.0.2 on 2026-02-25 10:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_recompensa', models.CharField(max_length=50)),
                ('monto_puntos_restados', models.IntegerField()),
                ('monto_dinero_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'db_table': 'canjes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion_texto', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('url_foto_portada', models.URLField(blank=True, null=True)),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('estado_operativo', models.BooleanField(default=True)),
                ('validado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Acopio',
                'verbose_name_plural': 'Centros de Acopio',
                'db_table': 'centros_acopio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('icono_url', models.URLField(blank=True, null=True)),
                ('puntos_por_unidad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'catalogo_materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilFirebase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('imagen_url', models.TextField(blank=True, null=True)),
                ('eco_puntos_saldo', models.IntegerField(default=0)),
                ('correo', models.TextField(unique=True)),
                ('tipo_usuario', models.TextField()),
                ('estado_cuenta', models.BooleanField(default=True)),
                ('qr_codigo', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil (Firebase)',
                'verbose_name_plural': 'Perfiles (Firebase)',
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntos_requeridos', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'db_table': 'recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'db_table': 'sugerencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario Admin',
                'verbose_name_plural': 'Usuarios Admin',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
